# Generated by Django 4.2.7 on 2023-11-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strana',
            old_name='wealth',
            new_name='aholi_soni',
        ),
    ]
